### ISSUE TITLE
I can't reproduce your issue posted on SO.

### ISSUE THREAD

**Issue by privefl** [YaohuiZeng/biglasso#1]
Concerning [your question on SO](http://stackoverflow.com/questions/39422346/rcpp-errors-occurred-when-using-template-function), I can't reproduce your error because I don't know exactly what you've changed compared to the current master branch.
Could you commit the changes you've tried? 
It would be easier to try to fix the problem.

Moreover, you should consider using devtools and roxygen2 for package development, it's really nice and elegant. Following the instruction in the book [R packages](http://r-pkgs.had.co.nz/) makes it easy.

**Comment by YaohuiZeng** [comment]
Hi Florian,

Thank you very much for taking a look. I just committed the changes. I suspect the error is due to the behavior of "XPtr", since there are some key words "PreserveStorage", "standard_delete_finalizer", etc. 

`__Z11get_elem_bmIdEdN4Rcpp4XPtrI9BigMatrixNS0_15PreserveStorageEXadL_ZNS0_25standard_delete_finalizerIS2_EEvPT_EEEEddii`

**Comment by privefl** [comment]
You don't have any R/RcppExports.R and src/RcppExports.cpp?

**Comment by YaohuiZeng** [comment]
No, I didn't. I used to have RcppExports.cpp, but later combined them into .cpp files. RcppExports.R file just include wrapper R functions for .Call(). The previous version (before adding templates) works well. So I am not sure whether having those RcppExports files make a difference.

I compile and install the package using R CMD commands.

**Comment by privefl** [comment]
I've tried to pass the accessor with the pointer as argument as it is done [there](http://gallery.rcpp.org/articles/using-bigmemory-with-rcpp/).
You can compare the codes [there](https://github.com/YaohuiZeng/biglasso/compare/master...privefl:master).
But it doesn't seem to change a thing.

One thing I don't understand is why your `utilities.cpp` has 
```
// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
```
while it seems to be modified by hand.

Moreover, I'm currently on Windows, which doesn't help with the debugging.

**Comment by YaohuiZeng** [comment]
Thanks for giving a try! I just did exactly the same thing, and failed too. 

I think the return type of functions like ``cd_gaussian_fit_cpp()`` should be ``Rcpp::List``, not ``SEXP``. So I changed that, but didn't help.

I also followed the link you pointed out but NOT passing matrix accessor as an argument, instead calling function like BigColSums<double>(xpMat) and it WORKED! (See code below) 

So really confused about where the bug is!!!!!!!!! 


```
// Logic for BigColSums.
template <typename T>
vector<int> BigColSums2(XPtr<BigMatrix> pMat) {
  
  // Create the vector we'll store the column sums in.
  MatrixAccessor<T> mat(*pMat);
  vector<int> colSums(pMat->ncol());
  for (size_t i=0; i < pMat->ncol(); i++) {
    for (size_t j=0; j < pMat->ncol(); j++) {
      colSums[i] += mat[i][j];
    }
  }
  return colSums;
}

// Dispatch function for BigColSums
//
// [[Rcpp::export]]
NumericVector BigColSums(SEXP pBigMat) {
  // First we have to tell Rcpp what class to use for big.matrix objects.
  // This object stores the attributes of the big.matrix object passed to it
  // by R.
  XPtr<BigMatrix> xpMat(pBigMat);
  
  // To access values in the big.matrix, we need to create a MatrixAccessor
  // object of the appropriate type. Note that in every case we are still
  // returning a NumericVector: this is because big.matrix objects only store
  // numeric values in R, even if their type is set to 'char'. The types
  // simply correspond to the number of bytes used for each element.
  switch(xpMat->matrix_type()) {
  case 1:
    return Rcpp::wrap(BigColSums2<char>(xpMat));
  case 2:
    return Rcpp::wrap(BigColSums2<short>(xpMat));
  case 4:
    return Rcpp::wrap(BigColSums2<int>(xpMat));
  case 8:
    return Rcpp::wrap(BigColSums2<double>(xpMat));
  // case 1:
  //   return BigColSums<char>(xpMat);
  // case 2:
  //   return BigColSums<short>(xpMat);
  // case 4:
  //   return BigColSums<int>(xpMat);
  // case 8:
  //   return BigColSums<double>(xpMat);
  default:
    // This case should never be encountered unless the implementation of
    // big.matrix changes, but is necessary to implement shut up compiler
    // warnings.
    throw Rcpp::exception("unknown type detected for big.matrix object!");
  }
}

```

**Comment by YaohuiZeng** [comment]
BTW, I removed the header lines in ``utilities.cpp`` as you pointed out. Sorry for the confusion. As you know, this file was previously automatically generated, but later I decided not to have RcppExports and just made manually changes in this file.

**Comment by privefl** [comment]
Last guess for me.
Do the functions in `utilities.cpp` need dispatchers too?

**Comment by YaohuiZeng** [comment]
I don't think so. See here https://github.com/aloysius-lim/bigrf/blob/master/src/growtree.cpp
