### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by vforget** [YaohuiZeng/biglasso#14]
I get the following error when using biglasso:

```
 *** caught segfault ***
address (nil), cause 'unknown'

Traceback:
 1: col.idx + 1
 2: biglasso(X.bm, Y, screen = "SSR-BEDPP", ncores = 16, verbose = TRUE,     dfmax = 50000, output.time = TRUE, max.iter = 100)
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault
```
It occurs when executing the following:

```
fit <- biglasso(X.bm, Y, screen = "SSR-BEDPP", ncores = 16, verbose=TRUE, dfmax=50000, output.time=TRUE, max.iter=100)
```

The data has 292074 features (SNPs) and 298769 individuals. biglasso runs for 92 lambdas. Excluding max.iter=100 makes the process run indefinitely, so we decided to set max.iter to 100 to see if we can get the training to complete (we assumed it ran indefinitely due be unable to converge on lambda 92 and thus run through all 1000 iterations, which we expect will take 5 days).

We have had no issues running biglasso on other similar datasets, albeit ones with many more individuals (~350,000) than features (~100,000). 

I am using the stable version:

```
install.packages("biglasso")
```
Package versions:

```
R version 3.4.1 (2017-06-30) -- "Single Candle"
       Package     Version
            BH    1.66.0-1
    data.table      1.11.4
        ncvreg      3.10-0
          Rcpp     0.12.17
 RcppArmadillo   0.8.500.0
            BH    1.65.0-1
      biglasso       1.3-6
     bigmemory      4.5.33
 bigmemory.sri       0.1.3
    data.table    1.10.4-3
        ncvreg       3.9-1
          Rcpp     0.12.15
 RcppArmadillo 0.8.300.1.0
```

Thanks,

Vince

**Comment by privefl** [comment]
Few quick questions:
- Are you using a filebacked big.matrix?
- Have you tried using less cores? On a subset of the data? Lowering `dfmax`?

**Comment by vforget** [comment]
Yes file backed big matrix. 

I can try 8 cores and dfmax at 20k. We get about 15k non zero beta on similar dataset.

**Comment by vforget** [comment]
This has worked previously using same data but more individuals, 340k, and more SNPs, 334k.

**Comment by vforget** [comment]
Update:

The following worked:

```
fit <- biglasso(X.bm, Y, screen = "SSR-BEDPP", ncores = 12, verbose=TRUE, dfmax=20000, output.time=TRUE, max.iter=100, lambda.min=0.001)
```

Is issue that not all parts of biglasso are out-of-core and therefore segfaults when it runs our of physical memory?

**Comment by vforget** [comment]
reducing dfmax did not produce good training results as we require more non-zero betas for good prediction, about 40k. I am using max.iter=100, dfmax=50000, and ncores=12 to see if thread count or max.iter was issue. Node has 16 threads.

If time permits I am glad to test this for you. Please send me personal message via email for specific ideas you may have.

**Comment by YaohuiZeng** [comment]
Sorry for late notice. Will look into this issue soon!

**Comment by vforget** [comment]
An update:

1. Original issue, which was not reported here, was that the training was stalling out at lambda 92, ie biglasso() would report it was on lambda 92 (verbose mode) and get stuck indefinitely (we tried to wait a few days).
2. To try and get it to work we tried the following, which is the subject of this thread:

```
fit <- biglasso(X.bm, Y, screen = "SSR-BEDPP", ncores = 16, verbose=TRUE, dfmax=50000, output.time=TRUE, max.iter=100)
```
This caused a segfault.

3. I now tried the following based on suggestion posted here:

```
fit <- biglasso(X.bm, Y, screen = "SSR-BEDPP", ncores = 12, verbose=TRUE, dfmax=50000, output.time=TRUE, max.iter=100)
```

This seems to have worked. biglasso() completed and results are valid.

So, seems like reducing core count worked. Odd that this was never an issue previously. We are using Amazon EC2 i3.4xlarge instance which worked previously on larger dataset (both SNPs and individuals). Limit on max.iter likely had no effect as the max # of iter reported by biglasso R object is 56.

Note that the original "stalling" was observed on two attempts, so not sure if this is sporadic/random issue.

**Comment by YaohuiZeng** [comment]
Not sure, but could be possible that using up all the cores for biglasso would cause huge overhead when your data is large. So I think it would be good to leave some cores for OS running.

Haven't tested biglasso on AWS. If I understand correctly, you cannot fully control AWS machines as they are shared. Other processes may cause yours stalling indefinitely, especially when you want to use up all the cores. Note that the parallel computing in biglasso is implemented via openMP, meaning that parallel computing can only be done on one shared-memory machine, but not distributed machines in AWS. Hope that helps a bit.

**Comment by vforget** [comment]
In the end, I suspect something changed on AWS, as biglasso has worked flawlessly for larger data sets previously. What may be related to this is that `Rscript script.R` no longer works as expected, ie it fails to load libraries, whereas `R -f script.R` works fine.  I was never able to track down the source of this issue. Feel free to close this issue as reducing the number of cores seems to solve it.
