### ISSUE TITLE
Running biglasso is much slower than before

### ISSUE THREAD

**Issue by privefl** [YaohuiZeng/biglasso#15]
Before, with my CentOS 7.2, it was very fast.
Now, I've upgraded to 7.4. I also tried with Linux Mint and with another computer.

Every run of biglasso (or my function that has a very similar code) is 1.5-10 times slower (sometimes more).

Have you any idea what could cause this huge drop in performance?
A missing library? Some difference in compiler optimizations?

This prevents me from finishing my simulations for a paper, any insight would be MUCH appreciated.

**Comment by YaohuiZeng** [comment]
Hmm, that's strange. seems to have something to do with your compile environment. The quick thing top of my head is [gcc compiler flag](https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html). Did you set any optimization before and not now? Or using a different compiler? Honestly, I don't have too much knowledge about compiler.

**Comment by privefl** [comment]
This is my best guest also.
I wonder if this comes from a change in handling inlining by new compilers (I think inlining is important for the C++ matrix accessor of big.matrix objects).
I'm making some tests and search and come back to you if I find a solution to this problem.

If anyone has another idea, please let me know.

**Comment by privefl** [comment]
Seems to be due to the sparse matrix accessor (`beta`) being much slower.

 I reported this issue [there](https://github.com/RcppCore/RcppArmadillo/issues/234).
