### ISSUE TITLE
Possible to set the intercept to 0

### ISSUE THREAD

**Issue by snowpong** [YaohuiZeng/biglasso#19]
Hi.

Thanks for making biglasso, it works well with bigmemory and memory-mapped files.

Is there a way, or hack, to set the intercept to 0? In `glmnet` you can set `intercept=FALSE` and the intercept(s) are set to zero.

**Comment by bsytffgj** [comment]
Was the problem solved or not? I'm eager for the answer too.

**Comment by snowpong** [comment]
@bsytffgj I never found a solution. But worked around / didn't need a solution for it in the end.

**Comment by pbreheny** [comment]
Duplicate of #37
