### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by Deleetdk** [YaohuiZeng/biglasso#2]
It would be very nice if there were a set of benchmarks comparing this implementation to other implementations in R, such as:

- https://cran.r-project.org/web/packages/BGLR/index.html
- https://cran.r-project.org/web/packages/glmnet/index.html
- https://cran.r-project.org/web/packages/ncvreg/index.html
- Many more https://cran.r-project.org/web/packages/available_packages_by_name.html

As far as I can tell, right now there's only the author's word for the efficiency.

**Comment by YaohuiZeng** [comment]
Thanks for your comment! I do have some preliminary results. I am still running some more benchmarking experiments, and will add those results soon.

**Comment by YaohuiZeng** [comment]
@Deleetdk, I updated some benchmark results. I will add some results regarding out-of-core computing. Feel free to let me know if you have any questions. Thanks!

**Comment by Deleetdk** [comment]
@YaohuiZeng Very nice!

Could you add the R code for doing the benchmarks? It would make it possible to 1) look for bugs, 2) expand upon it with other R LASSO packages.

Another question. Some of my colleagues use LASSO packages for other languages such as MATLAB. Have you run comparison benchmarks for these non-R packages?

**Comment by YaohuiZeng** [comment]
@Deleetdk I am still running more benchmarks, parallel computing, out-of-core computing, etc. I may open source some test code after I am done all experiments on my plan. But to reproduce results I've posted, there shouldn't be any fancy code. 

Thanks for pointing out comparisons with MATALB and BGLR. Unfortunately they are not on my list, and I don't have time to do that. This is something interesting to do though.

If you'd agree, I will close this issue. Again, thanks for your interests. Feel free to let me know if you have any further comments/suggestions, which are highly welcomed and appreciated.
