### ISSUE TITLE
Immediate crash on small problem

### ISSUE THREAD

**Issue by GabeAl** [YaohuiZeng/biglasso#22]
R MRO v3.5.3 and RStudio 1.2.1335 (both fresh installs), latest biglasso. Windows 10 (1903).

Biglasso works on the "colon" toy example with exact same script as below (except X and y are pulled out of the colon data object).

But, biglasso fails with a complete R crash (RStudio reports fatal error) with this:
[minimal.gz](https://github.com/YaohuiZeng/biglasso/files/3335862/minimal.gz)
Contains a tiny matrix and outcome vector, X and y.

```
library(biglasso)
load('F:/minimal.gz')
X.bm <- as.big.matrix(X)
fit.bin.lasso <- biglasso(X.bm, y, family = "binomial")
```

Yet it works perfectly with glmnet:
`fit.bin.lasso.glmnet <- glmnet(X, y, family = "binomial")`

```
> str(X)
 int [1:242, 1:2000] 1 1 1 1 1 1 1 1 1 1 ...
 - attr(*, "dimnames")=List of 2
  ..$ : NULL
  ..$ : NULL
> str(y)
 num [1:242] 1 1 1 1 1 1 1 1 1 1 ...
```

**Comment by privefl** [comment]
Nice minimal reprex!

The problem is that you have a matrix of integers, whereas only doubles are supported.
Use `X.bm <- as.big.matrix(X, type = "double")`.
