### ISSUE TITLE
Code and data used to produce benchmarks?

### ISSUE THREAD

**Issue by tomwenseleers** [YaohuiZeng/biglasso#23]
Was just wondering if it would be possible to release the code you used to produce the given benchmarks? Just asking because this would help to compare with other methods, and have everything 100% reproducible... And providing direct access to the R formatted real-world datasets would also be handy, just to be sure that other people would be using the exact same data... Would this be possible?

**Comment by pbreheny** [comment]
Code and data should be available here:

https://github.com/YaohuiZeng/biglasso_reproduce

Hope this helps; if you run into any problems, please reopen the issue.
