### ISSUE TITLE
predict.cv.biglasso - address 0x2b2da5f69ae0, cause 'memory not mapped'

### ISSUE THREAD

**Issue by prateeksasan1** [YaohuiZeng/biglasso#30]
I was trying to predict.cv.biglasso and got the following error : 

I havent been able to figure why this error occurs. Any ideas? 

 *** caught segfault ***
address 0x2b2da5f69ae0, cause 'memory not mapped'

Traceback:
 1: get_eta(X@address, as.integer(row.idx - 1), beta, beta.T@i, beta.T@j)
 2: predict.biglasso(object$fit, X = X, row.idx = row.idx, type = type,     lambda = lambda, which = which, ...)
 3: predict.cv.biglasso(fit1, X, type = "response", lambda = fit1$lambda[fit1$min])
 4: predict(fit1, X, type = "response", lambda = fit1$lambda[fit1$min])
 5: as.vector(predict(fit1, X, type = "response", lambda = fit1$lambda[fit1$min]))
 6: lasso_reg(test_sub, "101_anat_fmri.nii.gz", "afni_biglasso_selection_cv_fs+orig.BRIK.gz",     "penalty_bglasso_obj_fs.RData", "fs")
An irrecoverable exception occurred. R is aborting now ...
/var/spool/torque/mom_priv/jobs/11529146.owens-batch.ten.osc.edu.SC: line 43:  7338 Segmentation fault      Rscript /users/PAS1316/prateeksasan/hcp/wexner/controls_lasso_reg_oos.R

**Comment by pbreheny** [comment]
Can you provide a reproducible example?  This is impossible to debug if we can't see what's causing the error.

**Comment by privefl** [comment]
I think it would be useful to know e.g. which type of big.matrix object you are using and if e.g. you store it in some temp directory. I remember having a similar issue when that was the case.
