### ISSUE TITLE
Bug in cv.biglasso() triggered by edge case

### ISSUE THREAD

**Issue by nbenn** [YaohuiZeng/biglasso#32]
I ran into a minor issue when doing some testing (for which i use a very short lambda sequence): if `ind` if only of length 1, `E` and `Y` loose a dimension, which in turn causes `apply()` later to trip. I believe adding `drop = FALSE` would make the situation more robust.

**Comment by CHY-WANG** [comment]
@nbenn Thank you for noticing the problem and providing the solution. Your solution is merged.
