### ISSUE TITLE
Split available cores in cv.biglasso()

### ISSUE THREAD

**Issue by nbenn** [YaohuiZeng/biglasso#34]
I have a quick question: say you have 40 cores available for a 5-fold cv.biglasso() run. From having a quick look at your code, it seems to me that this would have 35 cores doing nothing. From a distance it seems straightforward, adding a couple of minor changes, to have each fold work with 8 cores (and thereby making such a scenario a bit more efficient). Or am I mistaken? I'm happy to prepare a PR adding such functionality.

**Comment by CHY-WANG** [comment]
@nbenn Thank you for help and it does noticeably improve the efficiency. Your pull request is merged.
