### ISSUE TITLE
Installation error on CRAN

### ISSUE THREAD

**Issue by privefl** [YaohuiZeng/biglasso#46]
It seems {biglasso} is getting lots of "Installation failed" on CRAN (cf. https://cran.r-project.org/web/checks/check_results_biglasso.html).

And this starts to propagate to my package as well.
It would be great if you could look into it.

**Comment by privefl** [comment]
It seems it now got removed from CRAN?

**Comment by pbreheny** [comment]
Sorry about this -- should be fixed soon, I think.

**Comment by pbreheny** [comment]
Back on CRAN now (version 1.5.0). Sorry about this!
