### ISSUE TITLE
Subsetting a

### ISSUE THREAD

**Issue by privefl** [YaohuiZeng/biglasso#6]
I think you should always subset `a` at https://github.com/YaohuiZeng/biglasso/blob/master/R/biglasso.R#L263.

An early stop can be the consequence of a saturated model (only in the logistic model) but also the consequence of the use of `dfmax`, which can appear in gaussian models too.
It then causes an error at https://github.com/YaohuiZeng/biglasso/blob/master/R/biglasso.R#L275 due to the length incompatibility between the two subtracted vectors.

**Comment by YaohuiZeng** [comment]
I think you are right. I will fix that. Thank you very much, @privefl !
